name: ci-affected

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

on: [push, pull_request]

jobs:
  myjob:
    runs-on: ubuntu-latest
    name: nx-affected-commands
    permissions:
      contents: 'read'
      actions: 'read'
      pull-requests: 'read'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      - name: Setup Node.js and Cache Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Nx Affected Test and Build
        run: npx nx affected --target=test,build --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }} --parallel=3 --configuration=ci
